services:
  # See https://render.com/docs/blueprint-spec for more info on render blueprints
  - type: web
    name: Ticket Analysis 1
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: "gunicorn --chdir src app:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
